import type { Page, Route } from "@playwright/test";

/**
 * The /assessments fixture: the REAL list, patched with the states the seed
 * does not have. Same pattern as `_students-fixture.ts` and `_locks-fixture.ts`:
 * the layout is tested on real rows, and only what the seed lacks is added.
 *
 * WHAT IS REAL. Every row, title, blueprint, item count, attempt limit and
 * salt date comes from the running API. Every "short" bank is the API's own
 * answer: locally all 96 act-1 items sit at `review`, 0 live, so every
 * blueprint is infeasible and names its real shortfall cells. That is a real
 * state and the page is tested on it as it is.
 *
 * WHAT IS ADDED, by title (ids are regenerated by every reset):
 *
 *   Stage 02 Check   closed        a window that ended
 *   Stage 03 Check   scheduled     a window that has not begun
 *   Stage 04 Check   open, bounded inside a window
 *   Stage 05 Check   one section   scoped to the seed's own section
 *   Stage 06 Check   rotated salt  rotated a day after it was set
 *   Stage 07 Check   bank fills    the one state no local bank can reach
 *   Stage 08 Check   no salt       the secrets row missing: Start would fail
 *
 * Prelim and Midterm are left exactly as the API sends them, because
 * `console-assessment-window.spec.ts`' original tests write REAL windows to
 * them and put them back.
 *
 * Seeded fixture names only. Not a spec: the leading underscore keeps
 * Playwright from collecting it.
 */

export interface Bank {
  totalItems: number; poolSize: number; enoughItems: boolean; satisfiable: boolean;
  shortfalls: Array<{ dimension: string; cell: string; need: number; have: number }>;
}
export interface Row {
  id: string; title: string; attemptsAllowed: number;
  opensAt: string | null; closesAt: string | null; createdAt: string;
  blueprintId: string; blueprintName: string; scope: "stage" | "final"; stageId: string | null;
  totalItems: number; sectionId: string | null; sectionCode: string | null;
  saltSetAt: string | null; saltRotatedAt: string | null;
  attempts: number; submitted: number; bank: Bank;
}
export interface List {
  assessments: Row[];
  blueprints: Array<{ id: string; name: string; scope: string; stageId: string | null; totalItems: number }>;
  sections: Array<{ id: string; code: string; term: string }>;
}

const DAY = 86_400_000;
const at = (offsetDays: number) => new Date(Date.now() + offsetDays * DAY).toISOString();

export const FIX = {
  closed: "Stage 02 Check",
  scheduled: "Stage 03 Check",
  bounded: "Stage 04 Check",
  scoped: "Stage 05 Check",
  rotated: "Stage 06 Check",
  fills: "Stage 07 Check",
  noSalt: "Stage 08 Check",
  /** Real, untouched, infeasible: the one the bank dialog reads. */
  real: "Prelim Examination",
} as const;

/** A bank that fills, shaped like the API's. */
export function filled(totalItems: number): Bank {
  return { totalItems, poolSize: totalItems + 4, enoughItems: true, shortfalls: [], satisfiable: true };
}

export function patch(list: List): List {
  const by = (t: string) => list.assessments.find((a) => a.title === t);
  const section = list.sections[0] ?? null;

  const closed = by(FIX.closed);
  if (closed) { closed.opensAt = at(-14); closed.closesAt = at(-7); closed.attempts = 3; closed.submitted = 2; }
  const scheduled = by(FIX.scheduled);
  if (scheduled) { scheduled.opensAt = at(4); scheduled.closesAt = at(11); }
  const bounded = by(FIX.bounded);
  if (bounded) { bounded.opensAt = at(-2); bounded.closesAt = at(5); }
  const scoped = by(FIX.scoped);
  if (scoped && section) { scoped.sectionId = section.id; scoped.sectionCode = section.code; }
  const rotated = by(FIX.rotated);
  if (rotated && rotated.saltSetAt) {
    rotated.saltRotatedAt = new Date(new Date(rotated.saltSetAt).getTime() + DAY).toISOString();
  }
  const fills = by(FIX.fills);
  if (fills) fills.bank = filled(fills.totalItems);
  const noSalt = by(FIX.noSalt);
  if (noSalt) { noSalt.saltSetAt = null; noSalt.saltRotatedAt = null; }
  return list;
}

export interface Writes {
  create: unknown[];
  window: unknown[];
  rotate: Array<{ url: string; body: unknown }>;
}

/**
 * Serve the patched list, pass feasibility through (patched to "fills" for the
 * one blueprint the fixture says fills), and INTERCEPT every write: creating an
 * assessment mints a salt, rotating one replaces it, and neither may touch the
 * database from a spec. `fail` makes a write refuse, for the error paths.
 */
export async function useFixture(
  page: Page,
  opts: { fail?: "create" | "rotate" | "window"; delayMs?: number; listStatus?: number } = {},
): Promise<{ writes: Writes; list: () => List | null }> {
  const writes: Writes = { create: [], window: [], rotate: [] };
  let last: List | null = null;
  let fillsBlueprint: string | null = null;

  await page.route("**/api/v1/console/assessments", async (route: Route) => {
    const req = route.request();
    if (req.method() === "POST") {
      writes.create.push(req.postDataJSON());
      if (opts.fail === "create") {
        return route.fulfill({ status: 400, json: { error: { code: "bad_request", message: "The closing time must be after the opening time." } } });
      }
      return route.fulfill({ status: 201, json: { id: "a55e0000-0000-4000-8000-000000000001" } });
    }
    if (opts.delayMs) await new Promise((r) => setTimeout(r, opts.delayMs));
    if (opts.listStatus && opts.listStatus >= 400) {
      return route.fulfill({ status: opts.listStatus, json: { error: { code: "internal", message: "The database did not answer." } } });
    }
    const res = await route.fetch();
    const list = patch((await res.json()) as List);
    fillsBlueprint = list.assessments.find((a) => a.title === FIX.fills)?.blueprintId ?? null;
    last = list;
    return route.fulfill({ response: res, json: list });
  });

  await page.route("**/api/v1/console/blueprints/*/feasibility", async (route: Route) => {
    const res = await route.fetch();
    const body = (await res.json()) as Bank & { blueprintId: string; name: string };
    if (fillsBlueprint && body.blueprintId === fillsBlueprint) {
      return route.fulfill({ response: res, json: { ...body, ...filled(body.totalItems) } });
    }
    return route.fulfill({ response: res, json: body });
  });

  await page.route("**/api/v1/console/assessments/*/rotate-salt", async (route: Route) => {
    writes.rotate.push({ url: route.request().url(), body: route.request().postDataJSON() });
    if (opts.fail === "rotate") {
      return route.fulfill({ status: 403, json: { error: { code: "forbidden", message: "Staff only." } } });
    }
    return route.fulfill({ status: 200, json: { ok: true, rotatedAt: new Date().toISOString() } });
  });

  await page.route("**/api/v1/console/assessments/*", async (route: Route) => {
    const req = route.request();
    if (req.method() !== "PATCH") return route.fallback();
    writes.window.push(req.postDataJSON());
    if (opts.fail === "window") {
      return route.fulfill({ status: 400, json: { error: { code: "bad_request", message: "An assessment cannot close before it opens." } } });
    }
    return route.fulfill({ status: 200, json: { ok: true } });
  });

  return { writes, list: () => last };
}
