import { useMemo, useState } from "react";
import { Download } from "lucide-react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from "recharts";
import { api } from "@/lib/api";
import { useAsync } from "@/lib/useAsync";
import { splitCsvLine } from "@/lib/csv";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Empty, ErrorNote, Loading } from "@/components/ui/empty";

/**
 * Gradebook — mastery per student per stage, and the class shape.
 *
 * The CSV is generated BY THE SERVER, not assembled here. One escaping
 * implementation, in one place, tested once: a student named `Dela Cruz, Juan`
 * has a comma in their name, and a gradebook that splits them across two
 * columns is a grading incident rather than a formatting bug.
 *
 * The chart answers a different question from the table. The table is "what did
 * this student get"; the chart is "did the class understand this chapter" — and
 * a stage where the whole class sits at 40% is a teaching signal, not a student
 * one.
 */
export function GradebookPage() {
  const { data, error, loading } = useAsync(() => api.gradebookCsv(), []);
  const stagesQ = useAsync(() => api.stages(), []);
  const [downloading, setDownloading] = useState(false);

  const parsed = useMemo(() => {
    if (!data) return null;
    const lines = data.trim().split("\n");
    if (lines.length === 0) return null;
    const header = splitCsvLine(lines[0]!);
    const rows = lines.slice(1).map(splitCsvLine).filter((r) => r.length === header.length);
    return { header, rows };
  }, [data]);

  const perStage = useMemo(() => {
    if (!parsed || parsed.rows.length === 0) return [];
    return parsed.header.slice(2).map((h, i) => {
      const values = parsed.rows.map((r) => Number(r[i + 2] ?? 0)).filter(Number.isFinite);
      const avg = values.length === 0 ? 0 : values.reduce((a, b) => a + b, 0) / values.length;
      return { stage: h.replace(/^stage_/, ""), avg: Math.round(avg) };
    });
  }, [parsed]);

  async function download() {
    setDownloading(true);
    try {
      const csv = await api.gradebookCsv();
      const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `octa-gradebook-${new Date().toISOString().slice(0, 10)}.csv`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setDownloading(false);
    }
  }

  if (loading) return <Loading what="the gradebook" />;
  if (error) return <ErrorNote message={error} />;

  const titleOf = (id: string) => stagesQ.data?.nodes.find((n) => n.id === id)?.title ?? "";

  return (
    <>
      <header className="mb-4 flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="mb-1 font-display text-2xl">Gradebook</h1>
          <p className="text-sm text-ink-muted">
            Mastery per stage, as a percentage. One column per gradeable chapter.
          </p>
        </div>
        <Button onClick={() => void download()} disabled={downloading}>
          <Download className="h-4 w-4" aria-hidden="true" />
          {downloading ? "Preparing…" : "Download CSV"}
        </Button>
      </header>

      {!parsed || parsed.rows.length === 0 ? (
        <Empty
          title="No grades yet"
          hint="The gradebook fills in as students complete stages. Until then there is nothing to average."
        />
      ) : (
        <>
          <Card className="mb-5">
            <CardHeader>
              <CardTitle>Class average by stage</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="h-64">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={perStage} margin={{ top: 4, right: 8, bottom: 4, left: -20 }}>
                    <CartesianGrid strokeDasharray="2 4" stroke="var(--line)" vertical={false} />
                    <XAxis
                      dataKey="stage"
                      tick={{ fill: "var(--ink-faint)", fontSize: 11 }}
                      stroke="var(--line-strong)"
                    />
                    <YAxis
                      domain={[0, 100]}
                      tick={{ fill: "var(--ink-faint)", fontSize: 11 }}
                      stroke="var(--line-strong)"
                    />
                    <Tooltip
                      cursor={{ fill: "var(--surface-2)" }}
                      contentStyle={{
                        background: "var(--surface-1)",
                        border: "1px solid var(--line-strong)",
                        borderRadius: "var(--radius-md)",
                        color: "var(--ink)",
                        fontSize: "var(--text-xs)",
                      }}
                      formatter={(v: number) => [`${v}%`, "Class average"]}
                      labelFormatter={(l: string) => `Stage ${l} ${titleOf(l)}`}
                    />
                    <Bar dataKey="avg" fill="var(--accent)" radius={[3, 3, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
              <p className="mt-2 text-xs text-ink-faint">
                A stage where the whole class sits low is a signal about the teaching, not about the
                students.
              </p>
            </CardContent>
          </Card>

          <div className="table-scroll rounded-lg border border-line bg-surface-1">
            <table className="w-full border-collapse text-sm">
              <caption className="sr-only">Mastery percentage per student per stage</caption>
              <thead>
                <tr className="border-b border-line-strong">
                  {parsed.header.map((h, i) => (
                    <th
                      key={h}
                      scope="col"
                      title={h.startsWith("stage_") ? titleOf(h.replace("stage_", "")) : undefined}
                      className={
                        i < 2
                          ? "sticky left-0 z-10 bg-surface-1 px-3 py-2 text-left text-xs font-semibold uppercase tracking-wide text-ink-muted"
                          : "px-2 py-2 text-center text-xs font-semibold text-ink-muted"
                      }
                    >
                      {h.startsWith("stage_") ? h.replace("stage_", "") : h.replace(/_/g, " ")}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {parsed.rows.map((r) => (
                  <tr key={r[0]} className="border-b border-line last:border-0 hover:bg-surface-2">
                    {r.map((cell, i) => (
                      <td
                        key={`${r[0]}-${i}`}
                        className={
                          i < 2
                            ? "sticky left-0 z-10 bg-surface-1 px-3 py-1.5 text-ink"
                            : "num px-2 py-1.5 text-center text-ink-muted"
                        }
                      >
                        {i < 2 ? cell : cell === "0" ? <span className="text-ink-faint">·</span> : cell}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}
    </>
  );
}
