import { describe, it, expect, beforeAll, beforeEach, afterAll } from "vitest";
import { pool, closePool, setup } from "./helpers/rls.js";
import { resetAll } from "./helpers/reset.js";

/**
 * Invariants that guard the item bank, tested against a P item shaped the way
 * the AUTHORED bank actually shapes one.
 *
 * Why this file exists.
 *
 * `helpers/bank.ts` seeds its type-P fixtures with `tolerance` and
 * `params_schema` filled in. No authored item carries either: measured on the
 * seeded bank, all 30 P items have a `solver_ref` and NULL for both columns.
 * The engine agrees with the bank, not the fixture — `resolveParameterized()`
 * reads `item.solverRef` and nothing else, then takes params from
 * `solver.draw()`, tolerance from `solver.tolerance`, sig figs, unit, stem and
 * rationale from the registry too.
 *
 * So the fixture satisfied INV-17 while every real item would have failed it,
 * and nothing noticed because no item has ever been `live`. The first approval
 * at `/items` would have put the database into a state its own invariant suite
 * calls illegal, and `run_invariants_nightly()` would have alerted on it.
 *
 * These tests seed the REAL shape. Before INV-17 was corrected, the first one
 * failed with `missing = 'tolerance'`.
 */

const OBJECTIVE = "07.3";

async function seedMinimalWorld(): Promise<void> {
  await resetAll();
  await setup(`
    insert into stages (id, act, ordinal, title, est_minutes, prereq, published, gradeable, archetype, levels)
    values ('07', 2, 7, 'Input/Output', 70, '{}', true, true, 'D', '{3,1}')
    on conflict (id) do nothing;

    insert into objectives (id, stage_id, code, bloom_level, level, competency, description)
    values ('${OBJECTIVE}', '07', '07.3', 'apply', 3, 'trace', 'Invariant probe objective')
    on conflict (id) do nothing;
  `);
}

/** A type-P item exactly as `sync-items.mjs` writes one: solver_ref, nothing else. */
async function insertAuthoredShapeP(slug: string, status: string): Promise<void> {
  await setup(`
    insert into items (slug, stage_id, objective_id, type, status, version, bloom,
                       stem_template, solver_ref, correct_spec, distractor_pool)
    values ('${slug}', '07', '${OBJECTIVE}', 'P'::item_type, '${status}'::item_status, 1, 'apply',
            'generated by solver', 'cycle-time', '{}'::jsonb, '[]'::jsonb);
  `);
}

async function offenders(id: string): Promise<number> {
  const { rows } = await pool.query(
    "select offending_count from run_invariants() where id = $1",
    [id],
  );
  return Number(rows[0]?.offending_count ?? -1);
}

beforeAll(async () => {
  await seedMinimalWorld();
});

// Each case owns the whole bank: a probe row left live by one test is counted
// by the next, which is how a shared-database suite reports a passing invariant
// as a failing one and sends you looking in the wrong place.
beforeEach(async () => {
  await setup("delete from items where slug like 'INV17-%';");
});

afterAll(async () => {
  await setup("delete from items where slug like 'INV17-%';");
  await closePool();
});

describe("INV-17 — a live type-P item is complete", () => {
  it("accepts the shape the authored bank actually uses: solver_ref, no tolerance, no params_schema", async () => {
    await insertAuthoredShapeP("INV17-authored-shape", "live");

    // The engine needs solver_ref and nothing else from the row. An invariant
    // that demands more than the engine reads blocks a correct bank.
    expect(await offenders("INV-17")).toBe(0);
  });

  it("still rejects a live type-P item with no solver_ref — the one thing the engine cannot do without", async () => {
    await setup(`
      insert into items (slug, stage_id, objective_id, type, status, version, bloom,
                         stem_template, correct_spec, distractor_pool)
      values ('INV17-no-solver', '07', '${OBJECTIVE}', 'P'::item_type, 'live'::item_status, 1, 'apply',
              'generated by solver', '{}'::jsonb, '[]'::jsonb);
    `);

    // resolveParameterized() throws "is type P but has no solver_ref" on this
    // row, so it must never be allowed to sit live in the bank.
    expect(await offenders("INV-17")).toBeGreaterThan(0);

    await setup("delete from items where slug = 'INV17-no-solver';");
  });

  it("counts every offender, not just the five it samples", async () => {
    // `run_invariants()` used to take count(*) inside its own `limit 5`, so any
    // number of broken rows reported as "5". The nightly job and the console
    // both print this figure as the severity of the problem.
    await setup(`
      insert into items (slug, stage_id, objective_id, type, status, version, bloom,
                         stem_template, correct_spec, distractor_pool)
      select 'INV17-bulk-' || g, '07', '${OBJECTIVE}', 'P'::item_type, 'live'::item_status, 1, 'apply',
             'generated by solver', '{}'::jsonb, '[]'::jsonb
      from generate_series(1, 9) g;
    `);

    expect(await offenders("INV-17")).toBe(9);
  });

  it("ignores a type-P item that is not live — an unapproved item is allowed to be incomplete", async () => {
    await setup(`
      insert into items (slug, stage_id, objective_id, type, status, version, bloom,
                         stem_template, correct_spec, distractor_pool)
      values ('INV17-draft-no-solver', '07', '${OBJECTIVE}', 'P'::item_type, 'draft'::item_status, 1, 'apply',
              'generated by solver', '{}'::jsonb, '[]'::jsonb);
    `);

    expect(await offenders("INV-17")).toBe(0);

    await setup("delete from items where slug = 'INV17-draft-no-solver';");
  });
});

describe("INV-16 — a live static item can be rendered", () => {
  /** A type-S item with `n` distractors, as `sync-items.mjs` writes one. */
  async function insertS(slug: string, n: number): Promise<void> {
    await setup(`
      insert into items (slug, stage_id, objective_id, type, status, version, bloom,
                         stem_template, correct_spec, distractor_pool, rationale_template)
      select '${slug}', '07', '${OBJECTIVE}', 'S'::item_type, 'live'::item_status, 1, 'remember',
             'A question?', '{"value":"the key"}'::jsonb,
             coalesce(jsonb_agg('wrong ' || g), '[]'::jsonb), 'Because.'
      from generate_series(1, ${n}) g;
    `);
  }

  it("accepts three distractors — the engine builds a 4-option paper and asks for exactly three", async () => {
    await setup("delete from items where slug like 'INV16-%';");
    await insertS("INV16-three", 3);
    expect(await offenders("INV-16")).toBe(0);
  });

  it("rejects two, which would throw at the moment a student pressed Start", async () => {
    await setup("delete from items where slug like 'INV16-%';");
    await insertS("INV16-two", 2);
    expect(await offenders("INV-16")).toBeGreaterThan(0);
    await setup("delete from items where slug like 'INV16-%';");
  });
});
