import { setup } from "./rls.js";
import { resetAll } from "./reset.js";

/**
 * A small but REAL item bank, seeded into the database so the attempt endpoints
 * have something to generate from.
 *
 * Deliberately mixes all three item types and both blueprint scopes, because the
 * interesting behaviours -- verdict withholding on a final, numeric grading on a
 * type-P item -- only appear when both exist.
 */

export interface BankWorld {
  studentA: string;
  studentB: string;
  teacher: string;
  sectionId: string;
  stageId: string;
  stageAssessmentId: string;
  finalAssessmentId: string;
  stageBlueprintTotal: number;
  finalBlueprintTotal: number;
}

export async function seedItemBank(): Promise<BankWorld> {
  await resetAll();

  const stageId = "07";
  const stageTotal = 8;
  const finalTotal = 6;

  const { rows } = await setup(
    `
    with
    sec as (
      insert into sections (code, term) values ('BSCPE-2A','2026-1') returning id
    ),
    ua as (
      insert into auth.users (id, email, raw_app_meta_data)
      values (gen_random_uuid(), 'a@octa-test.local', '{"role":"student"}'::jsonb) returning id
    ),
    ub as (
      insert into auth.users (id, email, raw_app_meta_data)
      values (gen_random_uuid(), 'b@octa-test.local', '{"role":"student"}'::jsonb) returning id
    ),
    ut as (
      insert into auth.users (id, email, raw_app_meta_data)
      values (gen_random_uuid(), 't@octa-test.local', '{"role":"teacher"}'::jsonb) returning id
    ),
    dir as (
      insert into student_directory (student_id, full_name, section_id, status, claimed_by, claimed_at)
      select '21-0001','Student A',(select id from sec),'claimed'::claim_status,(select id from ua), now()
      union all
      select '21-0002','Student B',(select id from sec),'claimed'::claim_status,(select id from ub), now()
      returning student_id
    ),
    prof as (
      insert into profiles (id, student_id, full_name, section_id, role)
      select (select id from ua), '21-0001','Student A',(select id from sec),'student'::user_role
      union all
      select (select id from ub), '21-0002','Student B',(select id from sec),'student'::user_role
      union all
      select (select id from ut), null,'Instructor',(select id from sec),'teacher'::user_role
      returning id
    ),
    obj as (
      insert into objectives (id, stage_id, code, bloom_level, level, competency, description)
      values ('07.1','07','07.1','remember',6,'read','Name the SI and binary prefixes'),
             ('07.2','07','07.2','understand',6,'read','Distinguish powers of 10 from powers of 2'),
             ('07.3','07','07.3','apply',2,'trace','Compute cycle time from frequency'),
             ('07.4','07','07.4','analyze',2,'trace','Compare two systems by cycle time')
      returning id
    ),
    -- Parameterized items: four per solver-backed objective.
    p_items as (
      insert into items (slug, stage_id, objective_id, type, status, version, bloom,
                         stem_template, solver_ref, tolerance, params_schema,
                         correct_spec, distractor_pool, reviewed_by, reviewed_at)
      select 'P-07-cycle-' || g, '07', '07.3', 'P'::item_type, 'live'::item_status, 1, 'apply',
             'generated by solver', 'cycle-time', 0.01, '{}'::jsonb,
             '{}'::jsonb, '[]'::jsonb, (select id from ut), now()
      from generate_series(1,6) g
      union all
      select 'P-07-units-' || g, '07', '07.2', 'P'::item_type, 'live'::item_status, 1, 'understand',
             'generated by solver', 'unit-convert', 0.005, '{}'::jsonb,
             '{}'::jsonb, '[]'::jsonb, (select id from ut), now()
      from generate_series(1,6) g
      returning id
    ),
    s_items as (
      insert into items (slug, stage_id, objective_id, type, status, version, bloom,
                         stem_template, correct_spec, distractor_pool, rationale_template,
                         reviewed_by, reviewed_at)
      select 'S-07-prefix-' || g, '07', '07.1', 'S'::item_type, 'live'::item_status, 1, 'remember',
             'Which prefix denotes 10^' || (g * 3) || '?',
             jsonb_build_object('value', (array['kilo','mega','giga','tera','peta','exa'])[g]),
             '["nano","micro","milli","centi","deci","hecto"]'::jsonb,
             'SI prefixes step by three orders of magnitude.',
             (select id from ut), now()
      from generate_series(1,6) g
      returning id
    ),
    g_items as (
      insert into items (slug, stage_id, objective_id, type, status, version, bloom,
                         stem_template, correct_spec, distractor_pool, rationale_template,
                         reviewed_by, reviewed_at)
      select 'G-07-order-' || g, '07', '07.4', 'G'::item_type, 'live'::item_status, 1, 'analyze',
             'Put these magnitudes in ascending order.',
             '{"order":["pico","nano","micro","milli","kilo","mega","giga"],"take":4}'::jsonb,
             '[]'::jsonb, 'Each step is three orders of magnitude.',
             (select id from ut), now()
      from generate_series(1,4) g
      returning id
    ),
    bp_stage as (
      insert into blueprints (name, scope, stage_id, total_items, constraints)
      values ('Stage 07 Check','stage','07', ${stageTotal},
              '{"by_type":{"S":3,"P":4,"G":1},
                "by_bloom":{"remember":3,"understand":2,"apply":2,"analyze":1},
                "max_per_objective":4,
                "exclude_non_gradeable_stages":true}'::jsonb)
      returning id
    ),
    bp_final as (
      insert into blueprints (name, scope, total_items, constraints)
      values ('Power-On Self Test','final', ${finalTotal},
              '{"by_type":{"S":2,"P":3,"G":1},
                "max_per_objective":4,
                "exclude_non_gradeable_stages":true}'::jsonb)
      returning id
    ),
    a_stage as (
      insert into assessments (blueprint_id, section_id, title, attempts_allowed)
      values ((select id from bp_stage), (select id from sec), 'Stage 07 Check', 20)
      returning id
    ),
    a_final as (
      insert into assessments (blueprint_id, section_id, title, attempts_allowed)
      values ((select id from bp_final), (select id from sec), 'Power-On Self Test', 20)
      returning id
    ),
    secrets as (
      insert into assessment_secrets (assessment_id, exam_salt)
      values ((select id from a_stage), encode(gen_random_bytes(32),'hex')),
             ((select id from a_final), encode(gen_random_bytes(32),'hex'))
      returning assessment_id
    )
    select (select id from ua) a, (select id from ub) b, (select id from ut) t,
           (select id from sec) s,
           (select id from a_stage) astage, (select id from a_final) afinal
    `,
  );

  const r = rows[0] as Record<string, string>;
  return {
    studentA: r.a!,
    studentB: r.b!,
    teacher: r.t!,
    sectionId: r.s!,
    stageId,
    stageAssessmentId: r.astage!,
    finalAssessmentId: r.afinal!,
    stageBlueprintTotal: stageTotal,
    finalBlueprintTotal: finalTotal,
  };
}
