/**
 * CSV in, CSV out.
 *
 * Both directions exist because of ONE fact: Philippine names are routinely
 * written `Dela Cruz, Juan Miguel`. A comma inside a field is the normal case
 * here, not an edge case, and a roster importer that splits on every comma
 * silently creates a student called "Dela Cruz" and throws away the given name.
 * That is a registration failure the student cannot fix and the teacher cannot
 * see, so it is tested rather than assumed.
 *
 * Writing CSV is deliberately NOT here — the gradebook export is generated by
 * `services/api`. One escaping implementation, in one place, tested once.
 */

export interface RosterLine {
  studentId: string;
  fullName: string;
}

export interface RosterParse {
  rows: RosterLine[];
  /** Lines that had no id or no name. Reported, never silently dropped. */
  bad: number;
}

/**
 * Parse a pasted roster.
 *
 * TWO formats are accepted, and the order they are tried in matters. See the
 * comment inside the loop.
 */

/**
 * An ID at the start of a line: digits, optionally with dashes.
 *
 * `23212905` and `21-1234-567` are both real university formats. Anchoring on
 * this is what lets a SPACE-separated paste work at all -- see below.
 */
// The name must begin with a real character, NOT a comma.
//
// Without `[^,\s]` the two rules fight: `21-1 , Santos, Maria` -- a comma line
// that happens to have a space before the comma -- matched here and produced the
// name ", Santos, Maria", comma and all. Requiring a non-comma first character
// makes that line fall through to the comma rule, where it belongs.
const LEADING_ID = /^([0-9][0-9-]{2,})[ 	]+([^,\s].*)$/;

export function parseRoster(text: string): RosterParse {
  const rows: RosterLine[] = [];
  let bad = 0;

  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line) continue;

    let id: string;
    let name: string;

    /*
     * TWO FORMATS, and the second is the one a teacher will actually paste.
     *
     * `23212905  Shem Joshua M. Dumpor` -- an ID and a name separated by
     * whitespace, which is how a university enrolment list arrives when copied
     * out of a PDF or a printed sheet. Requiring a comma would reject the
     * entire roster and give no clue why.
     *
     * It is safe to split on the first whitespace ONLY because the ID is a
     * rigid numeric code: the regex above will not match a name, so a line that
     * does not start with an ID falls through to the comma rule instead of
     * being mangled.
     */
    const spaced = LEADING_ID.exec(line);
    if (spaced) {
      id = spaced[1]!;
      name = spaced[2]!.trim();
    } else {
      // `ID,Full Name` -- and the name may itself contain commas, so the FIRST
      // comma is the only separator. "Dela Cruz, Juan Miguel" is one name.
      const comma = line.indexOf(",");
      if (comma === -1) {
        bad++;
        continue;
      }
      id = line.slice(0, comma).trim();
      name = line.slice(comma + 1).trim();
    }

    // A spreadsheet export quotes any field containing a comma, and doubles
    // quotes inside it. Unwrap before anything else looks at the name.
    if (name.startsWith('"') && name.endsWith('"') && name.length >= 2) {
      name = name.slice(1, -1).replace(/""/g, '"');
    }

    if (!id || !name) {
      bad++;
      continue;
    }
    // A header row is RECOGNISED, not assumed to be line 1 -- teachers paste
    // fragments from the middle of a spreadsheet as often as whole files.
    if (/^student_?\s?id$/i.test(id)) continue;

    rows.push({ studentId: id, fullName: name });
  }

  return { rows, bad };
}

/**
 * Read one line of RFC-4180 CSV, for the gradebook the server produced.
 *
 * The server quotes any field containing a comma, quote, or newline, and
 * doubles embedded quotes. This undoes exactly that and nothing more.
 */
export function splitCsvLine(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let quoted = false;

  for (let i = 0; i < line.length; i++) {
    const ch = line[i]!;
    if (quoted) {
      if (ch === '"' && line[i + 1] === '"') {
        cur += '"';
        i++;
      } else if (ch === '"') {
        quoted = false;
      } else {
        cur += ch;
      }
    } else if (ch === '"') {
      quoted = true;
    } else if (ch === ",") {
      out.push(cur);
      cur = "";
    } else {
      cur += ch;
    }
  }
  out.push(cur);
  return out;
}

/**
 * The lock cycle: auto → unlocked → locked → auto.
 *
 * `null` means auto — nobody has intervened and the curriculum decides. Kept
 * here rather than inline in the page so the cycle can be tested without
 * mounting a table of 19 × N buttons.
 */
export function nextLockState(
  override: "locked" | "unlocked" | null | undefined,
): "locked" | "unlocked" | "auto" {
  if (override === null || override === undefined) return "unlocked";
  return override === "unlocked" ? "locked" : "auto";
}
