/**
 * CSV in, CSV out.
 *
 * Both directions exist because of ONE fact: Philippine names are routinely
 * written `Dela Cruz, Juan Miguel`. A comma inside a field is the normal case
 * here, not an edge case, and a roster importer that splits on every comma
 * silently creates a student called "Dela Cruz" and throws away the given name.
 * That is a registration failure the student cannot fix and the teacher cannot
 * see, so it is tested rather than assumed.
 *
 * Writing CSV is deliberately NOT here — the gradebook export is generated by
 * `services/api`. One escaping implementation, in one place, tested once.
 */

export interface RosterLine {
  studentId: string;
  fullName: string;
}

export interface RosterParse {
  rows: RosterLine[];
  /** Lines that had no id or no name. Reported, never silently dropped. */
  bad: number;
}

/**
 * Parse a pasted roster.
 *
 * The format is `ID,Full Name` and the name may itself contain commas, so the
 * FIRST comma is the only separator: everything after it is the name. This is
 * not RFC-4180 — it is the shape a university export actually arrives in, where
 * the ID is a rigid code and the name is free text.
 *
 * A quoted name (`21-1,"Dela Cruz, Juan"`) is also accepted, because a teacher
 * who exports from a spreadsheet will get one.
 */
export function parseRoster(text: string): RosterParse {
  const rows: RosterLine[] = [];
  let bad = 0;

  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line) continue;

    const comma = line.indexOf(",");
    if (comma === -1) {
      bad++;
      continue;
    }

    const id = line.slice(0, comma).trim();
    let name = line.slice(comma + 1).trim();

    // A spreadsheet export quotes any field containing a comma, and doubles
    // quotes inside it. Unwrap before anything else looks at the name.
    if (name.startsWith('"') && name.endsWith('"') && name.length >= 2) {
      name = name.slice(1, -1).replace(/""/g, '"');
    }

    if (!id || !name) {
      bad++;
      continue;
    }
    // A header row is RECOGNISED, not assumed to be line 1 — teachers paste
    // fragments from the middle of a spreadsheet as often as whole files.
    if (/^student_?\s?id$/i.test(id)) continue;

    rows.push({ studentId: id, fullName: name });
  }

  return { rows, bad };
}

/**
 * Read one line of RFC-4180 CSV, for the gradebook the server produced.
 *
 * The server quotes any field containing a comma, quote, or newline, and
 * doubles embedded quotes. This undoes exactly that and nothing more.
 */
export function splitCsvLine(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let quoted = false;

  for (let i = 0; i < line.length; i++) {
    const ch = line[i]!;
    if (quoted) {
      if (ch === '"' && line[i + 1] === '"') {
        cur += '"';
        i++;
      } else if (ch === '"') {
        quoted = false;
      } else {
        cur += ch;
      }
    } else if (ch === '"') {
      quoted = true;
    } else if (ch === ",") {
      out.push(cur);
      cur = "";
    } else {
      cur += ch;
    }
  }
  out.push(cur);
  return out;
}

/**
 * The lock cycle: auto → unlocked → locked → auto.
 *
 * `null` means auto — nobody has intervened and the curriculum decides. Kept
 * here rather than inline in the page so the cycle can be tested without
 * mounting a table of 19 × N buttons.
 */
export function nextLockState(
  override: "locked" | "unlocked" | null | undefined,
): "locked" | "unlocked" | "auto" {
  if (override === null || override === undefined) return "unlocked";
  return override === "unlocked" ? "locked" : "auto";
}
